In [1]:
import numpy as np

print("NumPy imported successfully")

NumPy imported successfully


In [2]:
arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr1)

1D Array:
[10 20 30 40 50]


In [3]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]]


In [4]:
print(arr[0])     
print(arr[-1])    

NameError: name 'arr' is not defined

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [6]:
print(arr[0])     
print(arr[-1])  

10
50


In [7]:
print(arr[1:4])

[20 30 40]


In [8]:
a = np.array([10,20,30])
b = np.array([5,10,15])

print(a+b)  

[15 30 45]
[ 5 10 15]
[ 50 200 450]
[2. 2. 2.]


In [9]:
marks = np.array([80,90,85,95])

print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

350
87.5
95
80


In [10]:
print(arr.shape)
print(arr.size)
print(arr.dtype)

(5,)
5
int64
